CREATE TABLE TABLE_DEFINITION (
  ID INT NOT NULL,
  PHYSICAL_NAME VARCHAR(128) NOT NULL,
  LOGICAL_NAME VARCHAR(256) NOT NULL,
  CONSTRAINT TABLE_DEFINITION_PK PRIMARY KEY (ID),
  CONSTRAINT TABLE_DEFINITION_UK1 UNIQUE (PHYSICAL_NAME)
);
